server:
  servlet:
    session:
      timeout: 5m

spring:
  profiles:
    active: default
  data:
    mongodb:
      uri: mongodb+srv://pupajusang01:1234@gdgback.rbtvd.mongodb.net/?retryWrites=true&w=majority&appName=gdgback
      database: gdgback
  web:
    resources:
      static-locations: classpath:/static/, file:/app/images/

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}